In [1]:
# 1. Standard Imports
from scipy.stats import chi2_contingency
import polars as pl
import seaborn as sns
import matplotlib.pyplot as plt
from dbconfig import engine
"""%load_ext sql
%sql engine
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False"""
print("Environment Ready.")

Environment Ready.

In [11]:
%%sql
select count(*)
from matches
where toss_winner = winner

union all

select count(*)
from matches
where toss_winner != winner

union all

select count(*)
from matches;

   count
0    554
1    536
2   1095

In [7]:
%%sql
select toss_decision, count(*)
from matches
where toss_winner = winner
group by toss_decision;

  toss_decision  count
0           bat    177
1         field    377

In [10]:
%%sql
select
    toss_decision,
    count(*) as total_matches
from matches
group by toss_decision;

  toss_decision  total_matches
0           bat            391
1         field            704

In [12]:
from scipy.stats import chi2_contingency
import numpy as np

contingency = np.array([
    [177, 214],  # Bat: won, lost
    [377, 327]   # Field: won, lost
])

chi2, p, dof, expected = chi2_contingency(contingency)

print(f"Chi-Squared: {chi2}")
print(f"p-value: {p}")
print(f"Degrees of Freedom: {dof}")

Chi-Squared: 6.571677733078204
p-value: 0.01036142309365386
Degrees of Freedom: 1

In [5]:
chi2 = 1.7668181959226748
n = 158  # 164 + 74
k = 2

cramers_v = np.sqrt(chi2 / (n * (k - 1)))
print(f"Cramér's V: {cramers_v}")

Cramér's V: 0.10574683751810368

In [29]:
%%sql
select venue,
       count(distinct id) as match_count,
       sum(case when team1 = winner then 1 else 0 end) as team1_wins,
       round(100.0 * sum(case when team1 = winner then 1 else 0 end) / count(distinct id), 2) as team1_win_pct
from matches
group by venue
order by match_count desc
limit 5;

,venue,match_count,team1_wins,team1_win_pct
0,Wankhede Stadium,118,59,50.00
1,M Chinnaswamy Stadium,94,46,48.94
2,Eden Gardens,93,53,56.99
3,MA Chidambaram Stadium,85,52,61.18
4,"Rajiv Gandhi International Stadium, Uppal",62,31,50.00

In [3]:
%%sql
select venue, count(distinct id) as match_count,
       count(*) filter (where result = 'runs') as batting_result_count,
       count(*) filter (where result = 'wickets') as chasing_result_count,
       round(100.00 * count(*) filter (where result = 'runs') / count(distinct id) ,2) as batting_result_pct,
       round(100.00 * count(*) filter (where result = 'wickets') / count(distinct id) ,2) as chasing_result_pct
from matches
group by venue
order by match_count desc;

,venue,match_count,batting_result_count,chasing_result_count,batting_result_pct,chasing_result_pct
0,Wankhede Stadium,118,53,64,44.92,54.24
1,M Chinnaswamy Stadium,94,41,49,43.62,52.13
2,Eden Gardens,93,40,53,43.01,56.99
3,MA Chidambaram Stadium,85,47,36,55.29,42.35
4,"Rajiv Gandhi International Stadium, Uppal",62,27,34,43.55,54.84
5,"Punjab Cricket Association Stadium, Mohali",61,27,34,44.26,55.74
6,Feroz Shah Kotla,60,28,31,46.67,51.67
7,Sawai Mansingh Stadium,57,20,37,35.09,64.91
8,Dubai International Cricket Stadium,46,21,22,45.65,47.83
9,Dr DY Patil Sports Academy,37,17,20,45.95,54.05
10,Maharashtra Cricket Association Stadium,35,18,17,51.43,48.57
11,Arun Jaitley Stadium,30,16,13,53.33,43.33
12,Sheikh Zayed Stadium,29,11,16,37.93,55.17
13,Sharjah Cricket Stadium,28,10,18,35.71,64.29
14,Brabourne Stadium,27,14,13,51.85,48.15
15,Narendra Modi Stadium,24,9,15,37.50,62.50
16,Subrata Roy Sahara Stadium,16,10,6,62.50,37.50
17,Kingsmead,15,9,6,60.00,40.00
18,Rajiv Gandhi International Stadium,15,8,7,53.33,46.67
19,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,14,7,6,50.00,42.86
20,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,13,7,6,53.85,46.15
21,"Sardar Patel Stadium, Motera",12,6,5,50.00,41.67
22,SuperSport Park,12,4,8,33.33,66.67
23,Saurashtra Cricket Association Stadium,10,3,6,30.00,60.00
24,Holkar Cricket Stadium,9,1,8,11.11,88.89
25,Himachal Pradesh Cricket Association Stadium,9,5,4,55.56,44.44
26,New Wanderers Stadium,8,3,5,37.50,62.50
27,"Zayed Cricket Stadium, Abu Dhabi",8,3,5,37.50,62.50
28,Barabati Stadium,7,4,3,57.14,42.86
29,Newlands,7,4,2,57.14,28.57
30,St George's Park,7,3,4,42.86,57.14
31,JSCA International Stadium Complex,7,2,5,28.57,71.43
32,Shaheed Veer Narayan Singh International Stadium,6,2,4,33.33,66.67
33,Nehru Stadium,5,3,2,60.00,40.00
34,Maharaja Yadavindra Singh International Cricke...,5,2,3,40.00,60.00
35,Green Park,4,0,4,0.00,100.00
36,"Himachal Pradesh Cricket Association Stadium, ...",4,3,1,75.00,25.00
37,De Beers Diamond Oval,3,1,2,33.33,66.67
38,Buffalo Park,3,2,1,66.67,33.33
39,"Barsapara Cricket Stadium, Guwahati",3,2,1,66.67,33.33
40,"Vidarbha Cricket Association Stadium, Jamtha",3,2,1,66.67,33.33
41,OUTsurance Oval,2,1,1,50.00,50.00
42,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,2,2,0,100.00,0.00

In [8]:

venue_chasing.sort(by = ['match_count','chasing_result_pct'], descending = [True, True]).head(5)

shape: (5, 6)
┌────────────────┬─────────────┬────────────────┬────────────────┬────────────────┬────────────────┐
│ venue          ┆ match_count ┆ batting_result ┆ chasing_result ┆ batting_result ┆ chasing_result │
│ ---            ┆ ---         ┆ _count         ┆ _count         ┆ _pct           ┆ _pct           │
│ str            ┆ i64         ┆ ---            ┆ ---            ┆ ---            ┆ ---            │
│                ┆             ┆ i64            ┆ i64            ┆ f64            ┆ f64            │
╞════════════════╪═════════════╪════════════════╪════════════════╪════════════════╪════════════════╡
│ Wankhede       ┆ 118         ┆ 53             ┆ 64             ┆ 44.92          ┆ 54.24          │
│ Stadium        ┆             ┆                ┆                ┆                ┆                │
│ M Chinnaswamy  ┆ 94          ┆ 41             ┆ 49             ┆ 43.62          ┆ 52.13          │
│ Stadium        ┆             ┆                ┆                ┆                ┆                │
│ Eden Gardens   ┆ 93          ┆ 40             ┆ 53             ┆ 43.01          ┆ 56.99          │
│ MA Chidambaram ┆ 85          ┆ 47             ┆ 36             ┆ 55.29          ┆ 42.35          │
│ Stadium        ┆             ┆                ┆                ┆                ┆                │
│ Rajiv Gandhi   ┆ 62          ┆ 27             ┆ 34             ┆ 43.55          ┆ 54.84          │
│ International  ┆             ┆                ┆                ┆                ┆                │
│ Sta…           ┆             ┆                ┆                ┆                ┆                │
└────────────────┴─────────────┴────────────────┴────────────────┴────────────────┴────────────────┘

In [9]:
import numpy as np

contingency = np.array([
    [47, 36],  # Bat: won, lost
    [161, 200]   # Field: won, lost
])

chi2, p, dof, expected = chi2_contingency(contingency)

print(f"Chi-Squared: {chi2}")
print(f"p-value: {p}")
print(f"Degrees of Freedom: {dof}")

Chi-Squared: 3.4527850646392624
p-value: 0.06314528493229325
Degrees of Freedom: 1

In [10]:
chi2 = 3.4527850646392624
n = 85  # total Chidambaram matches
k = 2   # categories (runs vs wickets)

cramers_v = (chi2 / (n * (k - 1))) ** 0.5
print(f"Cramér's V: {cramers_v}")

Cramér's V: 0.20154652257099825